#!/usr/bin/env python3
"""
DEPRECATED — the roster is no longer generated by this script.

The boxer roster is now data-driven:

  * Canonical data:  src/_data/boxers.json
  * Rendered by Eleventy/Nunjucks loops in:
        - src/boxers.html      (full grid + division filter)
        - src/index.html       (featured strip; boxers with "featured": true)
  * Edited from the admin panel (Roster tab) via api/roster.js, which commits
    boxers.json back to GitHub and triggers a Vercel rebuild.

To change a fighter's record, KOs, BoxRec link, photo, champion/featured flag,
or to add/remove a boxer, use the admin dashboard (or edit src/_data/boxers.json
directly). Do NOT re-introduce HTML generation here — running it would clobber
the Nunjucks templates.

This stub intentionally writes nothing.
"""

import sys

if __name__ == "__main__":
    sys.stderr.write(__doc__)
    sys.exit(
        "\nupdate_roster.py is retired. Edit src/_data/boxers.json "
        "(or use the admin Roster tab) instead.\n"
    )
